name: Rust CI

on:
  push:
    branches:
      - main
      - enhancement**
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.**'
  pull_request:
    branches:
      - main

jobs:
  build_cache:
    name: Cache Rust ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo directory
        uses: ./.github/actions/cache_cargo
      - name: Build
        run: cargo build

  fmt_clippy:
    name: format and clippy
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Format code
        run: cargo fmt --all -- --check

  test:
    name: cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs: build_cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo directory
        uses: ./.github/actions/cache_cargo
      - name: Run tests
        run: cargo test -- --nocapture

